version: '3'

services:
  server:
    build: .
    volumes: 
      - .:/src/app
      - /src/app/node_modules
    depends_on:
      - 'database'
    ports: 
      - '4000:3001'
    command: 'npm start & npm run db:setup'

  database:
    container_name: main-products
    image: mongo:latest
    restart: always 
    
